[tool.poetry]
name = "kvault"
version = "0.1.0"
description = "Simple Miniature key-value datastore"
authors = ["BrianLusina <12752833+BrianLusina@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
gevent = "^22.10.2"
loguru = "^0.6.0"

[tool.poetry.dev-dependencies]
pylint = "^2.15.10"
pytest = "^7.2.1"
black = "^23.1.0"
pre-commit = "^3.0.4"
python-dotenv = "^0.21.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
