[tool.poetry]
name = "kvault"
version = "0.1.0"
description = "Simple Miniature key-value datastore"
authors = ["BrianLusina <12752833+BrianLusina@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
gevent = "^21.12.0"
loguru = "^0.6.0"

[tool.poetry.dev-dependencies]
pylint = "^2.15.2"
pytest = "^7.1.3"
black = "^22.8.0"
pre-commit = "^2.20.0"
python-dotenv = "^0.21.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
