name: Build

on:
  workflow_run:
    workflows:
      - "Tests"
    types:
      - completed

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Lint
    uses: BrianLusina/ci-workflows/.github/workflows/python-poetry-build.yml@main
    with:
      command: make build
      version: '3.10'
