name: Build

on:
  workflow_run:
    workflows:
      - "Tests"
    types:
      - completed

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    strategy:
      matrix:
        python-version: [ '3.10' ]
    name: Lint
    uses: BrianLusina/ci-workflows/.github/workflows/python-poetry-build.yml@main
    with:
      command: make build
      python-version: ${{ matrix.python-version }}
