name: Docker

on:
  workflow_run:
    workflows:
      - "Build"
    branches:
      - 'main'
    types:
      - completed

jobs:
  push_docker_hub:
    name: Docker Hub
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: SanctumLabs/ci-workflows/.github/workflows/docker_hub.yml@main
    secrets:
      registry: ${{ secrets.DOCKER_REGISTRY }}
      repository: ${{secrets.DOCKER_REPOSITORY}}
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

  push_docker_gcr:
    name: Github Container Registry
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: SanctumLabs/ci-workflows/.github/workflows/docker_gcr.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
