name: Lint

on:
  - push
  - pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Lint
    uses: brianlusina/ci-workflows/github/python-poetry-workflow.yml@main
    with:
      command: lint
