name: Lint

on:
  - push
  - pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Lint
    uses: BrianLusina/ci-workflows/.github/workflows/python-poetry-lint.yml@main
    with:
      command: make lint
      version: '3.10'
