name: Lint

on:
  - push
  - pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    strategy:
      matrix:
        python-version: [ '3.10' ]
    name: Lint
    uses: brianlusina/ci-workflows/.github/workflows/python/lint-poetry.yml@main
    with:
      command: make lint
      version: ${{ matrix.python-version }}
