name: Lint

on:
  - push
  - pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    strategy:
      matrix:
        python-version: [ '3.10' ]
    name: Lint
    uses: BrianLusina/ci-workflows/.github/workflows/python-poetry-lint.yml@main
    with:
      command: make lint
      python-version: ${{ matrix.python-version }}
