name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  lint:
    name: Publish
    uses: SanctumLabs/ci-workflows/.github/workflows/python-pypi-publish.yml@main
    with:
      command: make publish
      version: ${{ github.ref_name }}
    secrets:
      pypi_token: ${{ secrets.PYPI_TOKEN }}
