name: Publish

on:
  workflow_run:
    workflows:
      - "Build"
    types:
      - completed

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Publish
    uses: SanctumLabs/ci-workflows/.github/workflows/package/pypi/poetry-publish.yml@main
    with:
      command: make publish
    secrets:
      pypi_token: ${{ secrets.PYPI_TOKEN }}
