# Workflow only runs after the specified workflows have concluded running to completion. It then checks if they have
# been successful or failed. Appropriate messages are then sent afterwards on each event type
name: Slack Notification

on:
  workflow_run:
    workflows:
      - "Lint"
      - "Tests"
      - "Build"
      - "Publish"
      - "Docker"
      - "Release"
      - "RepoSync"
    types:
      - completed

jobs:
  slack:
    name: Slack Notification
    uses: SanctumLabs/ci-workflows/.github/workflows/slack_notification.yml@main
    with:
      slack_channel: cicd
    secrets:
      slack_webhook: ${{ secrets.PIPELINES_SLACK_WEBHOOK }}
