name: Tests

on:
  workflow_run:
    workflows:
      - "Lint"
    types:
      - completed

jobs:
  unittests:
    name: Lint
    uses: BrianLusina/ci-workflows/.github/workflows/python-poetry-test.yml@main
    with:
      command: make test
      version: '3.10'
