name: Tests

on:
  workflow_run:
    workflows:
      - "Lint"
    types:
      - completed

jobs:
  unittests:
    strategy:
      matrix:
        python-version: [ '3.10' ]
    name: Tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: SanctumLabs/ci-workflows/.github/workflows/python-test.yml@main
    with:
      command: make test
      python-version: ${{ matrix.python-version }}
