name: Tests

on:
  workflow_run:
    workflows:
      - "Lint"
    types:
      - completed

jobs:
  unittests:
    name: Unit Tests on ${{ matrix.python-version }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [ '3.6', '3.8', '3.9', '3.10' ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          pip install poetry
          poetry install          

      - name: Run tests
        run: make test-coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

      - name: Upload Test Coverage
        uses: codecov/codecov-action@v2

      - name: Run codacy-coverage-reporter
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh)
