name: Tests

on:
  workflow_run:
    workflows:
      - "Lint"
    types:
      - completed

jobs:
  unittests:
    strategy:
      matrix:
        python-version: [ '3.10' ]
    name: Lint
    uses: brianlusina/ci-workflows/.github/workflows/python-poetry-test.yml@main
    with:
      command: make test
      version: ${{ matrix.python-version }}
